spring.application.name=ProblemSolvingManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/problem_solving_manager
spring.datasource.username= postgres
spring.datasource.password= Password1!
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true